### PR TITLE
Fixing the loading problem

### LINKED ISSUE #35: GitHub is refusing to deliver data file under load
During the workshop, when many people access the file programmatically, they get "file does not exist"/404 or 408 permission denied after a while. We used this hotfix after a while:

https://github.com/aaronpeikert/repro-workshop/blob/0ade2e9f2a8f20556f526dd836ffd7b2c2d68b87/self-paced-source/00-getting-started.Rmd#L161-L186

@HannesDiemerling This must be solved properly before you can give the workshop at EPSY2023. Please ask if the problem is not clearly enough described to be solved.

### PR DESCRIPTION
**Pull request by HannesDiemerling**
Fixes #35

### CODE REVIEW

File: R/download_inflation.R [hunk 1]
```diff
@@ -1,21 +1,28 @@
...
+# Function to attempt Google Drive download
+downloadFromGoogle <- function() {
   download.file(
     "https://drive.google.com/uc?export=download&id=1czE3r1UEF21XvRGkXna0SE7yVvvrSiG3",
     fs::path_ext_set(inflation_raw_path, "rds")
   )
 }
+
+# Function to attempt Bank of England download and then process it
+downloadFromBankOfEngland <- function() {
```
Comment (aaronpeikert) [inline R/download_inflation.R]: r standard is not CamelCase but snake_case

**Comment by aaronpeikert** [comment]
- [x] Please do a function test within the posit cloud environment and GHA.
- [x] please update the RDS file so that it reflects the most recent XLSX

File: R/download_inflation.R [hunk 2]
```diff
@@ -1,21 +1,28 @@
 library(here)
+library(tidyverse)
 
 #----download----
 inflation_raw_path <- here("data", "raw", "inflation.xlsx")
 fs::dir_create(fs::path_dir(inflation_raw_path))
-if(FALSE){
```
Comment (aaronpeikert) [inline R/download_inflation.R:6]: please add a comment that this code requires to much RAM for posit and GHA
